2019-09-11 10:55:01.313747: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-09-11 10:55:01.352168: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
2019-09-11 10:55:01.359217: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x564774ce0af0 executing computations on platform Host. Devices:
2019-09-11 10:55:01.359273: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-11 10:55:01.490703: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x564771769440 executing computations on platform CUDA. Devices:
2019-09-11 10:55:01.490765: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): Quadro GV100, Compute Capability 7.0
2019-09-11 10:55:01.493183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
pciBusID: 0000:2d:00.0
totalMemory: 31.72GiB freeMemory: 30.51GiB
2019-09-11 10:55:01.493220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-09-11 10:55:01.497993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-11 10:55:01.498020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-09-11 10:55:01.498032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-09-11 10:55:01.500257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 29678 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2019-09-11 10:55:07.691289: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
/home/nramachandra/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
/home/nramachandra/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
/home/nramachandra/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())
/home/nramachandra/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/matplotlib/figure.py:445: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~
1287964
[      0       1       2 ... 1287961 1287962 1287963]
[[14.68299961 14.22999954 14.18299961 ... 14.215      14.258
   0.70141297]
 [14.69099998 14.53499985 14.23900032 ... 14.335      14.38
   0.44869809]
 [14.13899994 13.82800007 13.79300022 ... 13.613      13.661
   0.73302806]
 ...
 [11.91100025 11.63199997 11.58600044 ... 11.506      11.528
   1.10468381]
 [ 9.54800034  9.02200031  8.90299988 ...  8.825       8.943
   0.72845937]
 [12.15400028 11.87199974 11.81400013 ... 11.807      11.829
   1.2345698 ]]
68.96957827687106
-1.6096654796396705
here
[[0.49157759]
 [0.1483788 ]
 [0.2780788 ]
 ...
 [0.25592869]
 [0.0346365 ]
 [0.41355881]]
[60279, 12105, 160609, 132295, 135332, 5141, 186346, 199067, 29513, 56440]
[335866, 7820, 768853, 409800, 880864, 858767, 289531, 216237, 34494, 498910]
Traceback (most recent call last):
  File "T_PDM_p_all.py", line 594, in <module>
    plot_pred_mean(test_means,test_weights,test_std,ymax,ymin,y_test,train=False)
TypeError: plot_pred_mean() got an unexpected keyword argument 'train'
